### ISSUE TITLE
NetworkX 2.4 breaks 

### ISSUE THREAD

**Issue by j6k4m8** [rajatvd/manimnx#3]
Looks like there are a few API breaks with the [new networkx version](https://networkx.github.io/documentation/stable/release/release_2.4.html#deprecations). 

Main difference is that `nx.Graph#node[X]` is now `nx.Graph#nodes[x]` (nodeS, plural). Still using this repo? I'll push a fix :)

**Comment by rajatvd** [comment]
PR #1 fixes this.
